# PrivateAsk travis ci testing configuration
# GitHub: http://github.com/anestv/pa

language: php
php:
  - 5.5
  - 5.6

install: ./install.sh

before_script: sudo service apache2 restart

script:
  - cd test
  - python3 main.py

after_script:
  - cd ..
  - mysql -u root -e "DROP DATABASE privateask;"
  - sudo service apache2 stop
  - sudo service mysql stop
