# PrivateAsk travis ci testing configuration
# GitHub: http://github.com/anestv/pa

language: php
php:
  - 5.5
  - 5.6
install:
  - "./install.sh"

before_script:
  - "mysql-ctl start"
  - "apache2 -k restart"

script:
  - "cd test"
  - "python3 main.py"

after_script:
  - "cd .."
  - "apache2 -k stop"
  - "mysql-ctl stop"
